// Code generated by github.com/ngicks/go-f-helper/aferofs/cmd/implwrapper. DO NOT EDIT.
package closable

import (
	"io/fs"
)

func (recv *Closable[T]) Close() (err error) {
	if checkErr := recv.beforeEach("Close"); checkErr != nil {
		err = checkErr
		return
	}
	err = recv.inner.Close()
	return
}

func (recv *Closable[T]) Name() (s string) {
	_ = recv.beforeEach("Name")
	s = recv.inner.Name()
	return
}

func (recv *Closable[T]) Read(p []byte) (n int, err error) {
	if checkErr := recv.beforeEach("Read", p); checkErr != nil {
		err = checkErr
		return
	}
	n, err = recv.inner.Read(p)
	return
}

func (recv *Closable[T]) ReadAt(p []byte, off int64) (n int, err error) {
	if checkErr := recv.beforeEach("ReadAt", p, off); checkErr != nil {
		err = checkErr
		return
	}
	n, err = recv.inner.ReadAt(p, off)
	return
}

func (recv *Closable[T]) Readdir(count int) (fi []fs.FileInfo, err error) {
	if checkErr := recv.beforeEach("Readdir", count); checkErr != nil {
		err = checkErr
		return
	}
	fi, err = recv.inner.Readdir(count)
	return
}

func (recv *Closable[T]) Readdirnames(n int) (s []string, err error) {
	if checkErr := recv.beforeEach("Readdirnames", n); checkErr != nil {
		err = checkErr
		return
	}
	s, err = recv.inner.Readdirnames(n)
	return
}

func (recv *Closable[T]) Seek(offset int64, whence int) (n int64, err error) {
	if checkErr := recv.beforeEach("Seek", offset, whence); checkErr != nil {
		err = checkErr
		return
	}
	n, err = recv.inner.Seek(offset, whence)
	return
}

func (recv *Closable[T]) Stat() (fi fs.FileInfo, err error) {
	if checkErr := recv.beforeEach("Stat"); checkErr != nil {
		err = checkErr
		return
	}
	fi, err = recv.inner.Stat()
	return
}

func (recv *Closable[T]) Sync() (err error) {
	if checkErr := recv.beforeEach("Sync"); checkErr != nil {
		err = checkErr
		return
	}
	err = recv.inner.Sync()
	return
}

func (recv *Closable[T]) Truncate(size int64) (err error) {
	if checkErr := recv.beforeEach("Truncate", size); checkErr != nil {
		err = checkErr
		return
	}
	err = recv.inner.Truncate(size)
	return
}

func (recv *Closable[T]) Write(p []byte) (n int, err error) {
	if checkErr := recv.beforeEach("Write", p); checkErr != nil {
		err = checkErr
		return
	}
	n, err = recv.inner.Write(p)
	return
}

func (recv *Closable[T]) WriteAt(p []byte, off int64) (n int, err error) {
	if checkErr := recv.beforeEach("WriteAt", p, off); checkErr != nil {
		err = checkErr
		return
	}
	n, err = recv.inner.WriteAt(p, off)
	return
}

func (recv *Closable[T]) WriteString(s string) (n int, err error) {
	if checkErr := recv.beforeEach("WriteString", s); checkErr != nil {
		err = checkErr
		return
	}
	n, err = recv.inner.WriteString(s)
	return
}
