// Package synthfs implements an in-memory directory tree whose regular-file
// bytes are supplied by a [FileView] — a pointer to content in some backing
// storage (in-memory buffer, fs.FS file, byte range, generated bytes, …).
//
// synthfs lets callers assemble a tree that mixes heterogeneous sources
// without copying anything to disk, then expose it as
// [vroot.Root][vroot.File, *Root] for tar.Writer.AddFS / zip.Writer.AddFS via
// [vroot.ToIoFsRoot] without staging to a temp directory.
//
// A fresh [Root] is empty; populate it through the [vroot.Root] interface
// (Mkdir/Create/Symlink/…), through [Root.AddFile] / [Root.AddFS] to bind
// existing content as views, or by combining the two.
package synthfs
